"""Add testset_id to RatingResult

Revision ID: 02ca1ca00f27
Revises: af2d98ed9a33
Create Date: 2025-05-21 18:19:39.505096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02ca1ca00f27'
down_revision = 'af2d98ed9a33'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rating_results', sa.Column('testset_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'rating_results', 'testsets', ['testset_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rating_results', type_='foreignkey')
    op.drop_column('rating_results', 'testset_id')
    # ### end Alembic commands ### 