"""testset judge

Revision ID: af2d98ed9a33
Revises: 
Create Date: 2025-05-20 18:17:58.256329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af2d98ed9a33'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rating_results', sa.Column('llm_to_be_evaluated_type', sa.String(), nullable=True))
    op.add_column('rating_results', sa.Column('judge_llm_type', sa.String(), nullable=True))
    op.drop_column('rating_results', 'model_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rating_results', sa.Column('model_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('rating_results', 'judge_llm_type')
    op.drop_column('rating_results', 'llm_to_be_evaluated_type')
    # ### end Alembic commands ### 